version: "3.7"

services:
  elasticsearch:
    image: elasticsearch:7.9.0
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    ports:
      - 9200:9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - elknet
    restart: always

  kibana:
    image: kibana:7.9.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - elknet
    restart: always
  
#    logstash:
#      image: logstash:7.9.0
#      configs:
#        - source: logstash_config
#          target: /usr/share/logstash/config/logstash.yml
#        - source: logstash_pipeline
#          target: /usr/share/logstash/pipeline/logstash.conf
#      environment:
#        - LS_JAVA_OPTS: "-Xmx256m -Xms256m"
#        - ELASTICSEARCH_HOSTS: http://elasticsearch:9200
#        - xpack.monitoring.elasticsearch.hosts: [ "http://elasticsearch:9200" ]
#        - xpack.monitoring.enabled: false
#      ports:
#        - "5000:5000"
#        - "9600:9600"
#      depends_on:
#        - elasticsearch
#      networks:
#        - elknet
#      restart: always

volumes:
  elasticsearch-data:

networks:
  elknet:
  